# Generated by Django 4.2.23 on 2025-08-02 02:33

import cloudinary.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('POPULAR', 'Popular Brands'), ('NEW', 'New Arrivals'), ('SALE', 'Sale Items'), ('TRENDING', 'Trending'), ('CLASSIC', 'Classic Styles')], default=['POPULAR'], max_length=33)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('product_code', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
