# Generated by Django 4.2.23 on 2025-09-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="shoe",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
