# Generated by Django 4.2.23 on 2025-08-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCartForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
    ]
