# Generated by Django 4.2.23 on 2025-08-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_addtocartform_rename_contact_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocartform',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
    ]
