# Generated by Django 4.2.23 on 2025-08-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_addtocartform_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToCartForm',
        ),
    ]
