# Generated by Django 4.2.23 on 2025-08-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_addtocartform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shoe')),
            ],
        ),
    ]
