# Generated by Django 4.2.23 on 2025-08-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shoequantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoeQuantity',
        ),
    ]
