# Generated by Django 4.2.23 on 2025-08-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_cart_cartform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartform',
            name='user',
        ),
    ]
