# Generated by Django 4.2.23 on 2025-08-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cartform_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartForm',
        ),
    ]
