# Generated by Django 4.2.23 on 2025-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_cartform'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=2),
        ),
    ]
