# Generated by Django 4.2.16 on 2025-08-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
