# Generated by Django 4.2.16 on 2025-08-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_signupform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SignupForm",
        ),
    ]
