# shoe_data.py

shoes = [
    {
        "name": "Air Max Retro",
        "description": "Classic Air Max silhouette with updated cushioning.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1753072110/tlxhpcvmuvkl5kegp0o4.jpg",
        "price": 149.99,
        "categories": ['POPULAR', 'CLASSIC'],
        "slug": "air-max-retro",
        "product_code": "AMX001",
    },
    {
        "name": "Yeezy Boost 350",
        "description": "Comfort and style meet with this iconic Yeezy model.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1607956761/gzncd043kygmddjj0h3s.jpg",
        "price": 299.99,
        "categories": ['TRENDING', 'POPULAR'],
        "slug": "yeezy-boost-350",
        "product_code": "YZY350",
    },
    {
        "name": "Nike Dunk Low",
        "description": "Basketball roots with modern streetwear appeal.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1607959281/nfm0oyokfuyucvcyatd9.jpg",
        "price": 129.99,
        "categories": ['TRENDING', 'NEW'],
        "slug": "nike-dunk-low",
        "product_code": "NDL002",
    },
    {
        "name": "Adidas Samba OG",
        "description": "A timeless classic with retro design.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608212242/b7n27puannhgddk1mo7b.jpg",
        "price": 99.99,
        "categories": ['CLASSIC'],
        "slug": "adidas-samba-og",
        "product_code": "ADS003",
    },
    {
        "name": "Jordan 1 High",
        "description": "Legendary sneaker that started it all.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608215920/i3ybqdnrfxcajh6w59mk.webp",
        "price": 199.99,
        "categories": ['POPULAR', 'TRENDING'],
        "slug": "jordan-1-high",
        "product_code": "JDH004",
    },
    {
        "name": "New Balance 550",
        "description": "Vintage court style reborn.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608362716/yjzgyvhp9yutz2h8owma.png",
        "price": 139.99,
        "categories": ['TRENDING'],
        "slug": "new-balance-550",
        "product_code": "NB5505",
    },
    {
        "name": "Nike Air Force 1",
        "description": "Street style essential since 1982.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608383932/xjsy1yb9kkdvc27ytw5d.jpg",
        "price": 119.99,
        "categories": ['CLASSIC', 'POPULAR'],
        "slug": "nike-air-force-1",
        "product_code": "AF1006",
    },
    {
        "name": "Converse Chuck 70",
        "description": "Vintage-inspired with modern comfort upgrades.",
        "image": "https://res.cloudinary.com/demo/image/upload/v1699999999/chuck70.jpg",
        "price": 89.99,
        "categories": ['CLASSIC'],
        "slug": "converse-chuck-70",
        "product_code": "CC707",
    },
    {
        "name": "Vans Old Skool",
        "description": "Skater favorite with durable canvas and suede.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608390946/rbrb1dghygraszn5i3tx.png",
        "price": 74.99,
        "categories": ['SALE', 'CLASSIC'],
        "slug": "vans-old-skool",
        "product_code": "VNS008",
    },
    {
        "name": "Reebok Club C",
        "description": "Clean and minimal court shoe design.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608479263/tv1yzpa3jcosfmegbgku.jpg",
        "price": 84.99,
        "categories": ['SALE'],
        "slug": "reebok-club-c",
        "product_code": "RBC009",
    },
    {
        "name": "Nike ZoomX Vaporfly",
        "description": "Designed for speed and marathon runners.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608482680/hnvccutie8ahibsd5ddz.jpg",
        "price": 249.99,
        "categories": ['NEW'],
        "slug": "nike-zoomx-vaporfly",
        "product_code": "NZV010",
    },
    {
        "name": "Asics Gel-Kayano 30",
        "description": "Stability and comfort for daily runs.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608485356/b0zrq7qkduhbdloosukc.jpg",
        "price": 159.99,
        "categories": ['NEW'],
        "slug": "asics-gel-kayano-30",
        "product_code": "AGK011",
    },
    {
        "name": "Hoka One One Clifton 9",
        "description": "Cushioned and lightweight for long distances.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608523182/khcji0a6bpvfgektdgrr.jpg",
        "price": 144.99,
        "categories": ['NEW'],
        "slug": "hoka-clifton-9",
        "product_code": "HOK012",
    },
    {
        "name": "Salomon XT-6",
        "description": "Trail-ready with a fashion-forward edge.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608523642/ahfmqaieserd59pflbzb.jpg",
        "price": 195.00,
        "categories": ['TRENDING'],
        "slug": "salomon-xt-6",
        "product_code": "SLM013",
    },
    {
        "name": "Puma Suede Classic",
        "description": "Old-school style with soft suede.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608553902/ehgjwgt7mijix1tu7wkl.jpg",
        "price": 69.99,
        "categories": ['CLASSIC'],
        "slug": "puma-suede-classic",
        "product_code": "PMC014",
    },
    {
        "name": "Crocs Classic Clog",
        "description": "Iconic comfort meets casual style.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608887666/urvwdh8zlfh0mlhkiugj.jpg",
        "price": 49.99,
        "categories": ['SALE'],
        "slug": "crocs-clog",
        "product_code": "CRC015",
    },
    {
        "name": "On Cloud X",
        "description": "Versatile and sleek for gym or street.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608887543/dmnbasky7jvrnqvtmsbl.jpg",
        "price": 139.99,
        "categories": ['NEW'],
        "slug": "on-cloud-x",
        "product_code": "ONX016",
    },
    {
        "name": "Balenciaga Triple S",
        "description": "Chunky dad sneaker trend-setter.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1608917261/gugjjiwh9t4yej6fc1l8.jpg",
        "price": 950.00,
        "categories": ['TRENDING'],
        "slug": "balenciaga-triple-s",
        "product_code": "BLC017",
    },
    {
        "name": "Fila Disruptor II",
        "description": "Bulky 90s-inspired design.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1609002701/bqoehe4nggosby7ik2ub.jpg",
        "price": 89.99,
        "categories": ['SALE'],
        "slug": "fila-disruptor-ii",
        "product_code": "FLD018",
    },
    {
        "name": "Nike Cortez",
        "description": "Throwback West Coast classic.",
        "image": "https://res.cloudinary.com/dmq3kvtzu/image/upload/v1609087052/dlffw9rh7dxo0aihsfz9.jpg",
        "price": 89.99,
        "categories": ['CLASSIC'],
        "slug": "nike-cortez",
        "product_code": "NCZ019",
    },
]
